name: Build My App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Release new APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Rename APK
        run: |
          mv build/app/outputs/apk/release/app-arm64-v8a-release.apk build/app/outputs/apk/release/pabitra_banerjee-arm64-v8a-release.apk
          mv build/app/outputs/apk/release/app-armeabi-v7a-release.apk build/app/outputs/apk/release/pabitra_banerjee-armeabi-v7a-release.apk
          mv build/app/outputs/apk/release/app-x86_64-release.apk build/app/outputs/apk/release/pabitra_banerjee-x86_64-release.apk

      - name: Push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.0
          token: ${{ secrets.TOKEN }}
